(****************************************************************************


designs.inc

produced by Borland Resource Workshop


*****************************************************************************)

const
	BITMAP_1	=	1;
	BITMAP_2	=	2;
	BITMAP_3	=	3;
	BITMAP_4	=	4;
	BITMAP_5	=	5;
	BITMAP_6	=	6;
	BITMAP_7	=	7;
	BITMAP_8	=	8;
	BITMAP_9	=	9;
	BITMAP_10	=	10;
	BITMAP_11	=	11;
	BITMAP_12	=	12;
	BITMAP_13	=	13;
	BITMAP_14	=	14;
	BITMAP_15	=	15;
